ViksL = { }

-- general
	--ViksL.option_general = "General"
	ViksL.option_general_uiscale = "Auto UI Scale"
	ViksL.option_general_customuiscale = "UI Scale (if auto-scale is disabled)"
	ViksL.option_general_AutoRepair = "Auto Repair items"
	ViksL.option_general_AutoGreed = "Auto Greed"												
	ViksL.option_general_AutoDisenchant = "Auto Disenchant"	
	ViksL.option_general_AutoAcceptInvite = "Enable Auto-Invite (Friends and Guildmates)"
	ViksL.option_general_BlizzardsErrorFrameHiding = "Hide spamming error at the middle of your screen" 
	-- Unitframes
	ViksL.option_unitframes = "Unit Frames"
	ViksL.option_unitframes_enable = "Enable Unit Frames"
 	ViksL.option_unitframes_HealFrames = "Raid Frames for Healer" 
	ViksL.option_unitframes_showIndicators = "Buffs Indicator on Heal Raid Frames " 
	ViksL.option_unitframes_showAuraWatch = "Show buffs in corners" 
	ViksL.option_unitframes_ShowParty = "Show party frames (shown as 5man raid)" 
	ViksL.option_unitframes_ShowRaid = "Show raid frames" 
	ViksL.option_unitframes_RaidShowSolo = "Show raid frames even when solo" 
	ViksL.option_unitframes_RaidShowAllGroups = "Show raid groups 6, 7 and 8 (more than 25man raid)" 
	ViksL.option_unitframes_enableDebuffHighlight = "Enable *dispelable* debuff highlight for raid frames" 
	ViksL.option_unitframes_showRaidDebuffs = "Enable important debuff icons to show on raid units" 
	ViksL.option_unitframes_showtot = "Show target of target frame" 
	ViksL.option_unitframes_showpet = "Show pet frame" 
	ViksL.option_unitframes_showfocus = "Show focus frame" 
	ViksL.option_unitframes_showfocustarget = "Show focus target frame" 
	ViksL.option_unitframes_showBossFrames = "Show boss frame" 
	ViksL.option_unitframes_TotemBars = "Show Totem Bars"
	ViksL.option_unitframes_MTFrames = "Show main tank frames" 
	ViksL.option_unitframes_ArenaFrames = "Show arena frame" 
	ViksL.option_unitframes_Reputationbar = "Show Reputation bar" 
	ViksL.option_unitframes_Experiencebar = "Show Experience bar" 
	ViksL.option_unitframes_showPlayerAuras = "use a custom player buffs/debuffs frame instead of Blizzard's default" 
	ViksL.option_unitframes_ThreatBar = "Show Threat bar"
	ViksL.option_unitframes_showPortrait = "Show Portrait on player and target frames"
	ViksL.option_unitframes_showRunebar = "Show DK rune bar"
	ViksL.option_unitframes_showHolybar = "Show Paladin HolyPower bar" 
	ViksL.option_unitframes_showEclipsebar = "Show druid Eclipse bar" 
	ViksL.option_unitframes_showShardbar = "Show Warlock SoulShard bar" 
	ViksL.option_unitframes_RCheckIcon = "Show raid check icon" 
	ViksL.option_unitframes_Castbars = "Use built-in castbars" 
	ViksL.option_unitframes_showLFDIcons = "Show dungeon role icons in raid/party"
    ViksL.option_unitframes_HealthcolorClass = "Health color class"
	ViksL.option_unitframes_Powercolor = "Power bar by power color oO"
	ViksL.option_unitframes_showPartyFrames	 = "Show party frames"
	ViksL.option_unitframes_bigcastbar = "Big castbar"
	
	--raidframes
	ViksL.option_raidframes = "Raid Frames"
	ViksL.option_raidframes_enable = "Enable Raid Frames"
	ViksL.option_raidframes_scale = "Scale"
	ViksL.option_raidframes_width = "Width"
    ViksL.option_raidframes_height = "Height"
    ViksL.option_raidframes_fontsize = "Font size"
    ViksL.option_raidframes_fontsizeEdge = "Another font size"
    ViksL.option_raidframes_outline = "Font style(None, THINOUTLINE, MONOCHROME, OUTLINE, OUTLINEMONO)"
    ViksL.option_raidframes_solo = "Show player when solo"
    ViksL.option_raidframes_player = "Show self in group"
    ViksL.option_raidframes_party = "Show party frames (shown as 5man raid)"
    ViksL.option_raidframes_numCol = "Number of groups"
    ViksL.option_raidframes_numUnits = "Units per group"
    ViksL.option_raidframes_spacing = "Space between units"
    ViksL.option_raidframes_orientation = "Health Orientation"
    ViksL.option_raidframes_porientation = "PowerBar Orientation (VERTICAL, HORIZONTAL)"
    ViksL.option_raidframes_horizontal = "Horizontal groups"
    ViksL.option_raidframes_growth = "Growth Direction"
    ViksL.option_raidframes_reversecolors = "Reverse health colors"
    ViksL.option_raidframes_definecolors = "Health define colors"
    ViksL.option_raidframes_powerbar = "Power Bar"
    ViksL.option_raidframes_powerbarsize = "Power Bar size"
    ViksL.option_raidframes_outsideRange = "Out of range alpha"
    ViksL.option_raidframes_healtext = "Heal Text"
    ViksL.option_raidframes_healbar = "Heal Bar"
    ViksL.option_raidframes_healoverflow = "Heal overflow"
    ViksL.option_raidframes_healothersonly = "Others' heals only"
    ViksL.option_raidframes_healalpha = "Heal alpha"
    ViksL.option_raidframes_roleicon = "Role icon"
    ViksL.option_raidframes_indicatorsize = "Indicator size"
    ViksL.option_raidframes_symbolsize = "Bottom right indicator size"
    ViksL.option_raidframes_leadersize = "Leader, raid, role icon size"
    ViksL.option_raidframes_aurasize = "Aura size"
    ViksL.option_raidframes_multi = "Multiple headers"
    ViksL.option_raidframes_deficit = "Show missing health"
    ViksL.option_raidframes_perc = "Show health percentage"
    ViksL.option_raidframes_actual = "Show actual health"
    ViksL.option_raidframes_myhealcolor = "My Heal Color"
    ViksL.option_raidframes_otherhealcolor = "Other Heal Color"
    ViksL.option_raidframes_hpcolor = "Health color"
    ViksL.option_raidframes_hpbgcolor = "Health background color"
    ViksL.option_raidframes_powercolor = "Power color"
    ViksL.option_raidframes_powerbgcolor = "Power background color"
    ViksL.option_raidframes_powerdefinecolors = "Power define colors"
    ViksL.option_raidframes_colorSmooth = "Smooth Gradient"
    ViksL.option_raidframes_gradient = "Low health color"
    ViksL.option_raidframes_tborder = "Show target border"
    ViksL.option_raidframes_fborder = "Show focus border"
    ViksL.option_raidframes_afk = "AFK flag/timer"
    ViksL.option_raidframes_highlight = "Mouseover highlight"
    ViksL.option_raidframes_dispel = "Dispel icons"
    ViksL.option_raidframes_powerclass = "Color power by class"
    ViksL.option_raidframes_tooltip = "Show unit tooltip"
    ViksL.option_raidframes_sortName = "Sort by Name"
    ViksL.option_raidframes_sortClass = "Sort by Class"
    ViksL.option_raidframes_classOrder = "Class Order"
    ViksL.option_raidframes_hidemenu = "Hide Unit menu"
	
	
	--media
	ViksL.option_media = "Media" 	
	ViksL.option_media_font = "main font for Viks UI" 
	ViksL.option_media_pxfont = "1 px font for Viks UI" 
	ViksL.option_media_fontsize = "Size of font " 
	ViksL.option_media_bordercolor = "Border color" 
	ViksL.option_media_backdropcolor = "Background color" 
	ViksL.option_media_texture = "Texture" 
	ViksL.option_media_blank = "Background Texture" 
	--bags
	ViksL.option_bags = "Bags"	
	ViksL.option_bags_Enable = "Enable all in one bag"
	ViksL.option_bags_BagBars = "Enable bags panel"
	--datatext
	ViksL.option_datatext = "Data Text"
	ViksL.option_datatext_Durability = "Durability position (0 for disabled)"	
	ViksL.option_datatext_System = "Latency and FPS position (0 for disabled)"
	ViksL.option_datatext_Gold = "Gold position (0 for disabled)"
	ViksL.option_datatext_Guild = "Guild position (0 for disabled)"
	ViksL.option_datatext_Friends = "Friends position (0 for disabled)"
	ViksL.option_datatext_Bags = "Bags position (0 for disabled)"
	ViksL.option_datatext_Wowtime = "Time position (0 for disabled)"
	ViksL.option_datatext_Togglemenu = "ToggleMenu"
	ViksL.option_datatext_specswitcher = "Spec switcher"
	ViksL.option_datatext_Time24 = "Enable 24h time"
	ViksL.option_datatext_Localtime = "Use Local Time instead of Server Time"
	ViksL.option_datatext_classcolor = "Class color data text"
	ViksL.option_datatext_color = "If Class color data text false then choose color: "
	--loot
	ViksL.option_loot = "Loot"
	ViksL.option_loot_lootframe = "Enable loot window"
	ViksL.option_loot_rolllootframe = "Enable item roll window"
	ViksL.option_loot_position = "Позиция окна розыгрыша"
	--misk
	ViksL.option_enable = "Enable" 
	ViksL.option_addonmanager = "Addon Manager" 
	ViksL.option_togglemenu = "Toggle menu" 
	ViksL.option_togglemenu_buttonwidth = "Button width" 
	ViksL.option_togglemenu_buttonheight = "Button height" 
	ViksL.option_togglemenu_classcolor = "Classcolor border" 
	ViksL.option_classtimer = "Class Timer" 
	ViksL.option_cooldown = "cooldown" 
	ViksL.option_skinframe = "Skinframe" 	
	ViksL.option_filger = "Filger" 
	--chat
	ViksL.option_chat = "Chat"
	ViksL.option_chat_enable = "Enable"
	ViksL.option_chat_chatbar= "Enable chat bar" 
	ViksL.option_chat_chatframewidth = "Chat width"
	ViksL.option_chat_chatframeheight = "Chat height"
	ViksL.option_chat_editboxwidth = "Editbox width"
	ViksL.option_chat_editboxheight = "Editbox height"
	ViksL.option_chat_tabtextcolor = "Tab text color"
	ViksL.option_chat_ChatFrame = "Позиция чата"
    --buffs
	ViksL.option_buffs = "Buffs/Debuffs"
	ViksL.option_buffs_enable = "Enable"
	ViksL.option_buffs_iconsize = "Buffs size"
	ViksL.option_buffs_iconsizede = "Debuffs size"
	ViksL.option_buffs_timefontsize = "Time font size"
	ViksL.option_buffs_countfontsize = "Count font size" 
	ViksL.option_buffs_spacing = "Buffs spacing" 
	ViksL.option_buffs_debuffspacing = "Debuffs spacing" 
	ViksL.option_buffs_timeYoffset = "timeYoffset" 
	ViksL.option_buffs_BUFFS_PER_ROW = "Buffs per row" 
	ViksL.option_buffs_BUFFpos = "Buffs positions" 
	ViksL.option_buffs_DEBUFFpos = "Debuffs positions" 
	--addonskinning
	ViksL.option_addonsskins = "Addon Skins"
	ViksL.option_addonsskins_DBM = "DBM(/dbmskin apply)"
	ViksL.option_addonsskins_PallyPower = "PallyPower" 
	ViksL.option_addonsskins_Skada = "Skada" 
	ViksL.option_addonsskins_Recount = "Recount"
	ViksL.option_addonsskins_Omen = "Omen"
	ViksL.option_addonsskins_KLE = "KLE"	
	ViksL.option_addonsskins_Quartz = "Quartz"		
	ViksL.option_addonsskins_Bigwigs = "Bigwigs(/bigwigstest apply)"
	ViksL.option_addonsskins_DXE = "DXE(Deus Vox Encounters)"
	--nameplates
	ViksL.option_nameplates = "Nameplates"
	ViksL.option_nameplates_enable  = "Enable Nameplates"
	ViksL.option_nameplates_showlevel = "Display level text on nameplate for nameplates that belong to units that aren't your level."
	ViksL.option_nameplates_width = "Controls the width of the nameplate"
	ViksL.option_nameplates_showhealth = "Display health values on nameplates, this will also increase the size of the nameplate"
	ViksL.option_nameplates_enhancethreat = "Color the nameplate's healthbar by your current threat, Example: good threat color is used if your a tank when you have threat, opposite for DPS."
	ViksL.option_nameplates_combat = "Toggles the nameplates off when not in combat."
	ViksL.option_nameplates_goodcolor = "This is displayed when you have threat as a tank, if you don't have threat it is displayed as a DPS/Healer"
	ViksL.option_nameplates_badcolor = "This is displayed when you don't have threat as a tank, if you do have threat it is displayed as a DPS/Healer"
	ViksL.option_nameplates_goodtransitioncolor = "This color is displayed when gaining/losing threat, for a tank it would be displayed when gaining threat, for a dps/healer it would be displayed when losing threat"
	ViksL.option_nameplates_badtransitioncolor = "This color is displayed when gaining/losing threat, for a tank it would be displayed when losing threat, for a dps/healer it would be displayed when gaining threat"
	ViksL.option_nameplates_trackauras = "Tracks your debuffs on nameplates."
	ViksL.option_nameplates_trackccauras = "Tracks CC debuffs on nameplates from you or a friendly player"
	
	ViksL.option_Minimap = "Minimap"
	ViksL.option_Minimapenable = "Enable"
	ViksL.option_Minimapminimapsize = "Minimap size"
	ViksL.option_Map = "Map"
	ViksL.option_mapenable = "Enable"
	
	ViksL.option_markbar = "Mark bar"
	ViksL.option_markbarenable = "Enable mark bar"
	
	-- tooltip
	ViksL.option_tooltip = "Tooltip"
	ViksL.option_tooltip_enable = "Enable tooltip"
	ViksL.option_tooltip_hidecombat = "Hide tooltip in combat"
	ViksL.option_tooltip_hidebutton = "Hide tooltip on action bar buttons"
	ViksL.option_tooltip_hideuf = "Hide tooltip on unit frames"
	ViksL.option_tooltip_cursor = "Enable cursor tooltip"
	ViksL.option_tooltip_itemlevel = "Enable Target Item level on tooltip"
	ViksL.option_tooltip_spellid = "Enable Target SpellID on tooltip"
	ViksL.option_tooltip_talents = "Enable Target talents on tooltip"
	
	-- action bar
	ViksL.option_actionbar = "Action Bars"
	ViksL.option_actionbar_enable = "Enable action bar"
	ViksL.option_actionbar_hotkey = "Show hotkey on buttons"
	ViksL.option_actionbar_hideshapeshift = "Hide Shapeshift bar or Totem bar"
	ViksL.option_actionbar_bottomrows = "Main bars (1-3)"
	ViksL.option_actionbar_rightbars = "Right bar (0-3)"
	ViksL.option_actionbar_splitbar = "Side bars"
	ViksL.option_actionbar_buttonsize = "Size of the main action buttons"
	ViksL.option_actionbar_buttonspacing = "Spacing of the main action buttons"
	ViksL.option_actionbar_petbuttonsize = "Size of the pet action buttons"
	ViksL.option_actionbar_petbuttonspacing = "Spacing of the pet action buttons"
	ViksL.option_actionbar_swaptopbottombar = "Swap top bottom bars"
	ViksL.option_actionbar_macrotext = "Show macros text on buttons"
	ViksL.option_actionbar_verticalshapeshift = "Vertical Shift Bar"
	ViksL.option_actionbar_microbar = "Micro bar"
	ViksL.option_actionbar_mousemicro = "Mouseover for micro bar"
	ViksL.option_actionbar_showgrid = "Always show Grid on action bar"
	ViksL.option_actionbar_mainbarWidth = "MainBar Width(1-12)"
	ViksL.option_actionbar_ownshdbar = "Use an empty bar for shadow dance (rogue) instead of stealth bar"
	ViksL.option_actionbar_lowversion = "Other version for Action Bars"
	ViksL.option_actionbar_sidebarWidth = "SideBar Width(1-6), this option work if Other version for Action Bars = false"
	
	ViksL.option_misk = "Other"
	ViksL.option_raidutility = "Raid Utility"
	ViksL.option_BuffReminderRaidBuffs = "Reminder Raid Buffs"
	ViksL.option_Reminder = "Reminder Solo Buffs"
	ViksL.option_CooldownFlash = "Flashes an icon in the middle of your screen when a cooldown ends."
	ViksL.option_interrupts = "Announce interrupts in /say"
	ViksL.option_AutoScreen = "AutoScreen achievements"
	
	ViksL.option_reset = "Reset"
	ViksL.option_apply = "Apply"
	ViksL.option_close = "Close"
	ViksL.option_setsavedsetttings = "Set settings Per-Character"
	ViksL.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
	ViksL.option_resetall = "Are you sure you want to reset all of your settings to Default?"
	ViksL.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
	ViksL.option_makeselection = "You must make a selection before you can continue to config."
	
	ViksL.option_bottombars = "Bottom bars:"
	ViksL.option_rightbars = "Right bar(if off then damagebar on)"
	ViksL.option_nameplates_showlevel = "Show level"
	ViksL.option_raidcooldowns = "Raid cooldowns"
	ViksL.option_DamagebarWidth = "Damage bar width(1-12)"
	ViksL.option_Damagebar = "Damage bar"
	ViksL.option_sidebars = "Side bars"
	
----------------------------------------------------------------------------------------
--	Localization for enUS and enGB client
----------------------------------------------------------------------------------------
L_GUI_BUTTON_RESET = "Total Reset UI"
L_GUI_SET_SAVED_SETTTINGS = "Set settings Per-Character"
L_GUI_RESET_CHAR = "Are you sure you want to reset your character's settings for ViksUI?"
L_GUI_RESET_ALL = "Are you sure you want to reset all settings for ViksUI"
L_GUI_PER_CHAR = "Are you sure you want to change to or from 'Per Char Settings'?"
L_GUI_MAKE_SELECTION = "You must make a selection before you can continue to config."

-- General options
L_GUI_GENERAL_AUTOSCALE = "Auto UI Scale"
L_GUI_GENERAL_UISCALE = "UI Scale (if auto-scale is disabled)"
L_GUI_GENERAL_WELCOME_MESSAGE = "Welcome message in chat"
L_GUI_GENERAL_LAG_TOLERANCE = "Automatically update the Blizzard Custom Lag Tolerance option to your latency"

-- Miscellaneous options
L_GUI_MISC_MARKING = "Marks target when you push Shift"
L_GUI_MISC_INVKEYWORD = "Short keyword for invite (/ainv)"
L_GUI_MISC_SPIN_CAMERA = "Spin camera while afk"
L_GUI_MISC_SPIN_CAMERA_ANIM = "Animation nr for modell"
L_GUI_MISC_VEHICLE_MOUSEOVER = "Vehicle frame on mouseover"
L_GUI_MISC_QUEST_AUTOBUTTON = "Quest/item auto button (from the list)"
L_GUI_MISC_RAID_TOOLS = "Raid tools"
L_GUI_MISC_PROFESSION_TABS = "Professions tabs on tradeskill/trade frames"
L_GUI_MISC_HIDE_BG_SPAM = "Remove Boss Emote spam during BG"
L_GUI_MISC_ITEM_LEVEL = "Item level on character slot buttons"
L_GUI_MISC_ALREADY_KNOWN = "Colorizes recipes/mounts/pets/toys that is already known"
L_GUI_MISC_DISENCHANTING = "Milling, Prospecting and Disenchanting by Alt + click"
L_GUI_MISC_SUM_BUYOUTS = "Sum up all current auctions"
L_GUI_MISC_CLICK_CAST = "Simple click2cast spell binder"
L_GUI_MISC_CLICK_CAST_FILTER = "Ignore Player and Target frames for click2cast"
L_GUI_MISC_MOVE_BLIZZARD = "Move some Blizzard frames"
L_GUI_MISC_COLOR_PICKER = "Improved ColorPicker"
L_GUI_MISC_ENCHANTMENT_SCROLL = "Enchantment scroll on TradeSkill frame"
L_GUI_MISC_ARCHAEOLOGY = "Archaeology artifacts and cooldown"
L_GUI_MISC_CHARS_CURRENCY = "Tracks your currency tokens across multiple characters"
L_GUI_MISC_ARMORY_LINK = "Add Armory link in UnitPopupMenus (It breaks set focus)"
L_GUI_MISC_MERCHANT_ITEMLEVEL = "Show item level for weapons and armor in merchant"
L_GUI_MISC_MINIMIZE_MOUSEOVER = "Mouseover for quest minimize button"
L_GUI_MISC_HIDE_BANNER = "Hide Boss Banner Loot Frame"
L_GUI_MISC_HIDE_TALKING_HEAD = "Hide Talking Head Frame"
L_GUI_MISC_COMBAT_ANIM = "Show text animation for combat toggle"

-- Announcements options
L_GUI_ANNOUNCEMENTS = "Announcements"
L_GUI_ANNOUNCEMENTS_DRINKING = "Announce in chat when arena enemy is drinking"
L_GUI_ANNOUNCEMENTS_INTERRUPTS = "Announce in party/raid when you interrupt"
L_GUI_ANNOUNCEMENTS_SPELLS = "Announce in party/raid when you cast some spell (from the list)"
L_GUI_ANNOUNCEMENTS_SPELLS_FROM_ALL = "Check spells cast from all members"
L_GUI_ANNOUNCEMENTS_TOY_TRAIN = "Announce some annoying toys"
L_GUI_ANNOUNCEMENTS_SAYS_THANKS = "Says thanks for some spells"
L_GUI_ANNOUNCEMENTS_PULL_COUNTDOWN = "Pull countdown announce (/pc #)"
L_GUI_ANNOUNCEMENTS_FLASK_FOOD = "Announce the usage of flasks and food"
L_GUI_ANNOUNCEMENTS_FLASK_FOOD_AUTO = "Auto announce when ReadyCheck"
L_GUI_ANNOUNCEMENTS_FLASK_FOOD_RAID = "Announce to raid channel"
L_GUI_ANNOUNCEMENTS_FEASTS = "Announce Feasts/Souls/Repair Bots cast"
L_GUI_ANNOUNCEMENTS_PORTALS = "Announce Portals/Ritual of Summoning cast"
L_GUI_ANNOUNCEMENTS_BAD_GEAR = "Check bad gear in instance"
L_GUI_ANNOUNCEMENTS_SAFARI_HAT = "Check Safari Hat"

-- Automation options
L_GUI_AUTOMATION = "Automation"
L_GUI_AUTOMATION_RELEASE = "Auto release the spirit in battlegrounds"
L_GUI_AUTOMATION_SCREENSHOT = "Take screenshot when player get achievement"
L_GUI_AUTOMATION_SOLVE_ARTIFACT = "Auto popup for solve artifact"
L_GUI_AUTOMATION_ACCEPT_INVITE = "Auto accept invite"
L_GUI_AUTOMATION_DECLINE_DUEL = "Auto decline duel (/disduel to temporarily disable)"
L_GUI_AUTOMATION_ACCEPT_QUEST = "Auto accept quest (disabled if hold Shift)"
L_GUI_AUTOMATION_AUTO_COLLAPSE = "Auto collapse ObjectiveTrackerFrame in instance"
L_GUI_AUTOMATION_AUTO_COLLAPSE_RELOAD = "Auto collapse ObjectiveTrackerFrame after reload"
L_GUI_AUTOMATION_SKIP_CINEMATIC = "Auto skip cinematics/movies (disabled if hold Ctrl)"
L_GUI_AUTOMATION_AUTO_ROLE = "Auto set your role"
L_GUI_AUTOMATION_CANCEL_BAD_BUFFS = "Auto cancel various buffs"
L_GUI_AUTOMATION_TAB_BINDER = "Auto change Tab key to only target enemy players"
L_GUI_AUTOMATION_LOGGING_COMBAT = "Auto enables combat log text file in raid instances"
L_GUI_AUTOMATION_CURRENCY_CAP = "Auto popup for currency cap"
L_GUI_AUTOMATION_BUFF_ON_SCROLL = "Cast buff on mouse scroll (from the list)"
L_GUI_AUTOMATION_OPEN_ITEMS = "Auto opening of items in bag"

-- Skins options
L_GUI_SKINS = "Stylization"
L_GUI_SKINS_BLIZZARD = "Enable styling Blizzard frames"
L_GUI_SKINS_MINIMAP_BUTTONS = "Enable styling addons icons on minimap"
L_GUI_SKINS_CLCR = "Enable styling CLCRet"
L_GUI_SKINS_CLCP = "Enable styling CLCProt"
L_GUI_SKINS_COMBUSTION_HELPER = "Enable styling CombustionHelper"
L_GUI_SKINS_BW = "Enable styling BigWigs"
L_GUI_SKINS_DBM = "Enable styling DBM"
L_GUI_SKINS_DBM_MOVABLE = "Allow to move DBM bars"
L_GUI_SKINS_DXE = "Enable styling DXE"
L_GUI_SKINS_OMEN = "Enable styling Omen"
L_GUI_SKINS_RECOUNT = "Enable styling Recount"
L_GUI_SKINS_BLOOD_SHIELD_TRACKER = "Enable styling BloodShieldTracker"
L_GUI_SKINS_DOMINOS = "Enable styling Dominos"
L_GUI_SKINS_FLYOUT_BUTTON = "Enable styling FlyoutButtonCustom"
L_GUI_SKINS_NUG_RUNNING = "Enable styling NugRunning"
L_GUI_SKINS_OVALE = "Enable styling OvaleSpellPriority"
L_GUI_SKINS_CLIQUE = "Enable styling Clique"
L_GUI_SKINS_ACE3 = "Ace3 options elements skin"
L_GUI_SKINS_PP = "Enable styling PallyPower"
L_GUI_SKINS_CAPPING = "Enable styling Capping"
L_GUI_SKINS_COOL_LINE = "Enable styling CoolLine"
L_GUI_SKINS_ATLASLOOT = "Enable styling AtlasLoot"
L_GUI_SKINS_TINY_DPS = "Enable styling TinyDPS"
L_GUI_SKINS_FACE_SHOOTER = "Enable styling FaceShooter"
L_GUI_SKINS_MAGE_NUGGETS = "Enable styling MageNuggets"
L_GUI_SKINS_NPCSCAN = "Enable styling NPCScan"
L_GUI_SKINS_VANASKOS = "Enable styling VanasKoS"
L_GUI_SKINS_WEAK_AURAS = "Enable styling WeakAuras"
L_GUI_SKINS_SKADA = "Enable styling Skada"
L_GUI_SKINS_MY_ROLE_PLAY = "Enable styling MyRolePlay"
L_GUI_SKINS_ARH = "Enable styling Archaeology Helper"
L_GUI_SKINS_POSTAL = "Enable styling Postal" -- Need review
L_GUI_SKINS_OPIE = "Enable styling OPie" -- Need review
L_GUI_SKINS_REMATCH = "Enable styling Rematch" -- Need review
L_GUI_SKINS_LS_TOASTS = "Enable styling ls: Toasts" -- Need review

-- Combat text options
L_GUI_COMBATTEXT = "Combat Text"
L_GUI_COMBATTEXT_ENABLE = "Enable Combat Text"
L_GUI_COMBATTEXT_BLIZZ_HEAD_NUMBERS = "Use blizzard damage/healing output (above mob/player head)"
L_GUI_COMBATTEXT_DAMAGE_STYLE = "Change default damage/healing font above mobs/player heads (you need to restart WoW to see changes)"
L_GUI_COMBATTEXT_DAMAGE = "Show outgoing damage in it's own frame"
L_GUI_COMBATTEXT_HEALING = "Show outgoing healing in it's own frame"
L_GUI_COMBATTEXT_HOTS = "Show periodic healing effects in healing frame"
L_GUI_COMBATTEXT_OVERHEALING = "Show outgoing overhealing"
L_GUI_COMBATTEXT_PET_DAMAGE = "Show your pet damage"
L_GUI_COMBATTEXT_DOT_DAMAGE = "Show damage from your dots"
L_GUI_COMBATTEXT_DAMAGE_COLOR = "Display damage numbers depending on school of magic"
L_GUI_COMBATTEXT_CRIT_PREFIX = "Symbol that will be added before crit"
L_GUI_COMBATTEXT_CRIT_POSTFIX = "Symbol that will be added after crit"
L_GUI_COMBATTEXT_ICONS = "Show outgoing damage icons"
L_GUI_COMBATTEXT_ICON_SIZE = "Icon size of spells in outgoing damage frame, also has effect on dmg font size"
L_GUI_COMBATTEXT_TRESHOLD = "Minimum damage to show in damage frame"
L_GUI_COMBATTEXT_HEAL_TRESHOLD = "Minimum healing to show in incoming/outgoing healing messages"
L_GUI_COMBATTEXT_SCROLLABLE = "Allows you to scroll frame lines with mousewheel"
L_GUI_COMBATTEXT_MAX_LINES = "Max lines to keep in scrollable mode (more lines = more memory)"
L_GUI_COMBATTEXT_TIME_VISIBLE = "Time(seconds) a single message will be visible"
L_GUI_COMBATTEXT_DK_RUNES = "Show deathknight rune recharge"
L_GUI_COMBATTEXT_KILLINGBLOW = "Tells you about your killingblows"
L_GUI_COMBATTEXT_MERGE_AOE_SPAM = "Merges multiple aoe damage spam into single message"
L_GUI_COMBATTEXT_MERGE_MELEE = "Merges multiple auto attack damage spam"
L_GUI_COMBATTEXT_DISPEL = "Tells you about your dispels"
L_GUI_COMBATTEXT_INTERRUPT = "Tells you about your interrupts"
L_GUI_COMBATTEXT_DIRECTION = "Scrolling Direction('top'(goes down) or 'bottom'(goes up))"
L_GUI_COMBATTEXT_SHORT_NUMBERS = "Use short numbers ('25.3k' instead of '25342')"

-- Buffs reminder options
L_GUI_REMINDER = "Buffs Reminder"
L_GUI_REMINDER_SOLO_ENABLE = "Show missing self buffs"
L_GUI_REMINDER_SOLO_SOUND = "Warning sound notification for self buffs reminder"
L_GUI_REMINDER_SOLO_SIZE = "Self buffs icon size"
L_GUI_REMINDER_RAID_ENABLE = "Show missing raid buffs"
L_GUI_REMINDER_RAID_ALWAYS = "Show buffs reminder always"
L_GUI_REMINDER_RAID_SIZE = "Raid buffs icon size"
L_GUI_REMINDER_RAID_ALPHA = "Transparent icons when the buffs is present"

-- Raid cooldowns options
L_GUI_COOLDOWN_RAID = "Raid Cooldowns"
L_GUI_COOLDOWN_RAID_ENABLE = "Enable raid cooldowns"
L_GUI_COOLDOWN_RAID_HEIGHT = "Raid cooldowns bars height"
L_GUI_COOLDOWN_RAID_WIDTH = "Raid cooldowns bars width (if the icon is enabled, width+28)"
L_GUI_COOLDOWN_RAID_SORT = "Raid cooldowns sort upwards bars"
L_GUI_COOLDOWN_RAID_EXPIRATION = "Sort by expiration time"
L_GUI_COOLDOWN_RAID_SHOW_SELF = "Show self cooldowns"
L_GUI_COOLDOWN_RAID_ICONS = "Raid cooldowns icons"
L_GUI_COOLDOWN_RAID_IN_RAID = "Show raid cooldowns in raid zone"
L_GUI_COOLDOWN_RAID_IN_PARTY = "Show raid cooldowns in party zone"
L_GUI_COOLDOWN_RAID_IN_ARENA = "Show raid cooldowns in arena zone"

-- Enemy cooldowns options
L_GUI_COOLDOWN_ENEMY = "Enemy Cooldowns"
L_GUI_COOLDOWN_ENEMY_ENABLE = "Enable enemy cooldowns"
L_GUI_COOLDOWN_ENEMY_SIZE = "Enemy cooldowns icon size"
L_GUI_COOLDOWN_ENEMY_DIRECTION = "Enemy cooldowns icon direction (RIGHT|LEFT|UP|DOWN)"
L_GUI_COOLDOWN_ENEMY_EVERYWHERE = "Show everywhere enemy cooldowns"
L_GUI_COOLDOWN_ENEMY_IN_BG = "Show enemy cooldowns in bg zone"
L_GUI_COOLDOWN_ENEMY_IN_ARENA = "Show enemy cooldowns in arena zone"

-- Pulse cooldowns options
L_GUI_COOLDOWN_PULSE = "Pulse Cooldowns"
L_GUI_COOLDOWN_PULSE_ENABLE = "Show cooldowns pulse"
L_GUI_COOLDOWN_PULSE_SIZE = "Cooldowns pulse icon size"
L_GUI_COOLDOWN_PULSE_SOUND = "Warning sound notification"
L_GUI_COOLDOWN_PULSE_ANIM_SCALE = "Animation scaling"
L_GUI_COOLDOWN_PULSE_HOLD_TIME = "Max opacity hold time"
L_GUI_COOLDOWN_PULSE_THRESHOLD = "Minimal threshold time"

-- Threat options
L_GUI_THREAT = "Threat Bars"
L_GUI_THREAT_ENABLE = "Enable threat bars"
L_GUI_THREAT_HEIGHT = "Threat bars height"
L_GUI_THREAT_WIDTH = "Threat bars width"
L_GUI_THREAT_ROWS = "Number of threat bars"
L_GUI_THREAT_HIDE_SOLO = "Show only in party/raid"

-- Tooltip options
L_GUI_TOOLTIP = "Tooltip"
L_GUI_TOOLTIP_ENABLE = "Enable tooltip"
L_GUI_TOOLTIP_SHIFT = "Show tooltip when Shift is pushed"
L_GUI_TOOLTIP_CURSOR = "Tooltip above cursor"
L_GUI_TOOLTIP_ICON = "Item icon in tooltip"
L_GUI_TOOLTIP_HEALTH = "Numeral health value"
L_GUI_TOOLTIP_HIDE = "Hide tooltips for actions bars"
L_GUI_TOOLTIP_HIDE_COMBAT = "Hide tooltip in combat"
L_GUI_TOOLTIP_TALENTS = "Show tooltip talents"
L_GUI_TOOLTIP_ACHIEVEMENTS = "Comparing achievements in tooltip"
L_GUI_TOOLTIP_TARGET = "Target player in tooltip"
L_GUI_TOOLTIP_TITLE = "Player title in tooltip"
L_GUI_TOOLTIP_REALM = "Player realm name in tooltip"
L_GUI_TOOLTIP_RANK = "Player guild-rank in tooltip"
L_GUI_TOOLTIP_ARENA_EXPERIENCE = "Player PvP experience in arena"
L_GUI_TOOLTIP_SPELL_ID = "Spell ID"
L_GUI_TOOLTIP_RAID_ICON = "Raid icon"
L_GUI_TOOLTIP_WHO_TARGETTING = "Display who is targetting the unit that is in your party/raid"
L_GUI_TOOLTIP_ITEM_COUNT = "Item count"
L_GUI_TOOLTIP_UNIT_ROLE = "Unit role"
L_GUI_TOOLTIP_INSTANCE_LOCK = "Your instance lock status in tooltip"
L_GUI_TOOLTIP_ITEM_TRANSMOGRIFY = "Displays items can not be transmogrified"

-- Chat options
L_GUI_CHAT_ENABLE = "Enable chat"
L_GUI_CHAT_BACKGROUND = "Enable chat background"
L_GUI_CHAT_BACKGROUND_ALPHA = "Alpha of chat background"
L_GUI_CHAT_SPAM = "Removing some systems spam('Player1' won duel 'Player2')"
L_GUI_CHAT_GOLD = "Removing some players spam"
L_GUI_CHAT_WIDTH = "Chat width"
L_GUI_CHAT_HEIGHT = "Chat height"
L_GUI_CHAT_BAR = "Lite Button Bar for switch chat channel"
L_GUI_CHAT_BAR_MOUSEOVER = "Lite Button Bar on mouseover"
L_GUI_CHAT_TIMESTAMP = "Timestamp coloring"
L_GUI_CHAT_WHISP = "Sound when whisper"
L_GUI_CHAT_SKIN_BUBBLE = "Skin Blizzard chat bubbles"
L_GUI_CHAT_CL_TAB = "Show Combat Log tab"
L_GUI_CHAT_TABS_MOUSEOVER = "Chat tabs on mouseover"
L_GUI_CHAT_STICKY = "Remember last channel"
L_GUI_CHAT_DAMAGE_METER_SPAM = "Merge damage meter spam in one line-link"

-- Bag options
L_GUI_BAGS = "Bags"
L_GUI_BAGS_ENABLE = "Enable bags"
L_GUI_BAGS_ILVL = "Show item level for weapons and armor"
L_GUI_BAGS_BUTTON_SIZE = "Buttons size"
L_GUI_BAGS_BUTTON_SPACE = "Buttons space"
L_GUI_BAGS_BANK = "Number of columns in bank"
L_GUI_BAGS_BAG = "Number of columns in main bag"
L_GUI_BAGS_BUTTONS = "Show sort/deposit/Artifact buttons"

-- Minimap options
L_GUI_MINIMAP_ENABLE = "Enable minimap"
L_GUI_MINIMAP_ICON = "Tracking icon"
L_GUI_GARRISON_ICON = "Garrison icon"
L_GUI_MINIMAP_SIZE = "Map size"
L_GUI_MINIMAP_HIDE_COMBAT = "Hide minimap in combat"
L_GUI_MINIMAP_TOGGLE_MENU = "Show toggle menu"

-- Map options
L_GUI_MAP_BG_STYLIZATION = "BG map stylization"
L_GUI_MAP_BOSS_COUNT = "Show boss count in World Map"
L_GUI_MAP_EXPLORE = "Tracking Explorer and Lore Master achievements in World Map"
L_GUI_MAP_FOG_OF_WAR = "Remove fog of war on World Map"

-- Loot options
L_GUI_LOOT_ENABLE = "Enable loot frame"
L_GUI_LOOT_ROLL_ENABLE = "Enable group loot frame"
L_GUI_LOOT_ICON_SIZE = "Icon size"
L_GUI_LOOT_WIDTH = "Loot frame width"
L_GUI_LOOT_AUTOGREED = "Enable auto-greed/disenchant for green item at max level"
L_GUI_LOOT_AUTODE = "Auto confirm disenchant"

-- Nameplate options
L_GUI_NAMEPLATE_ENABLE = "Enable nameplates"
L_GUI_NAMEPLATE_COMBAT = "Automatically show nameplates in combat"
L_GUI_NAMEPLATE_HEALTH = "Numeral health value"
L_GUI_NAMEPLATE_CASTBAR = "Show nameplate castbar"
L_GUI_NAMEPLATE_HEIGHT = "Nameplates height"
L_GUI_NAMEPLATE_WIDTH = "Nameplates width"
L_GUI_NAMEPLATE_DISTANCE = "Show nameplates for units within this range"
L_GUI_NAMEPLATE_AD_HEIGHT = "Additional height for selected nameplate"
L_GUI_NAMEPLATE_AD_WIDTH = "Additional width for selected nameplate"
L_GUI_NAMEPLATE_CASTBAR_NAME = "Show castbar name"
L_GUI_NAMEPLATE_THREAT = "Enable threat feature, automatically changes by your role"
L_GUI_NAMEPLATE_CLASS_ICON = "Icons by class in PvP"
L_GUI_NAMEPLATE_NAME_ABBREV = "Display abbreviated names"
L_GUI_NAMEPLATE_CLAMP = "Clamp nameplates to the top of the screen when outside of view"
L_GUI_NAMEPLATE_GOOD_COLOR = "Good threat color, varies depending if your a tank or dps/heal"
L_GUI_NAMEPLATE_NEAR_COLOR = "Losing/Gaining threat color"
L_GUI_NAMEPLATE_BAD_COLOR = "Bad threat color, varies depending if your a tank or dps/heal"
L_GUI_NAMEPLATE_OFFTANK_COLOR = "Offtank threat color"
L_GUI_NAMEPLATE_SHOW_DEBUFFS = "Show debuffs (from the list)"
L_GUI_NAMEPLATE_SHOW_BUFFS = "Show buffs above player nameplate (from the list)"
L_GUI_NAMEPLATE_DEBUFFS_SIZE = "Debuffs size"
L_GUI_NAMEPLATE_HEALER_ICON = "Show icon above enemy healers nameplate in battlegrounds"
L_GUI_NAMEPLATE_TOTEM_ICONS = "Show icon above enemy totems nameplate"

-- ActionBar options
L_GUI_ACTIONBAR_ENABLE = "Enable action bars"
L_GUI_ACTIONBAR_HOTKEY = "Show hotkey on buttons"
L_GUI_ACTIONBAR_MACRO = "Show macro name on buttons"
L_GUI_ACTIONBAR_GRID = "Show empty action bar buttons"
L_GUI_ACTIONBAR_BUTTON_SIZE = "Buttons size"
L_GUI_ACTIONBAR_BUTTON_SPACE = "Buttons space"
L_GUI_ACTIONBAR_SPLIT_BARS = "Split the fifth bar on two bars on 6 buttons"
L_GUI_ACTIONBAR_CLASSCOLOR_BORDER = "Enable classcolor border for buttons"
L_GUI_ACTIONBAR_TOGGLE_MODE = "Enable toggle mode"
L_GUI_ACTIONBAR_HIDE_HIGHLIGHT = "Hide proc highlight"
L_GUI_ACTIONBAR_BOTTOMBARS = "Number of action bars on the bottom (1, 2 or 3)"
L_GUI_ACTIONBAR_RIGHTBARS = "Number of action bars on right (0, 1, 2 or 3)"
L_GUI_ACTIONBAR_RIGHTBARS_MOUSEOVER = "Right bars on mouseover"
L_GUI_ACTIONBAR_PETBAR_MOUSEOVER = "Petbar on mouseover (only for horizontal petbar)"
L_GUI_ACTIONBAR_PETBAR_HIDE = "Hide pet bar"
L_GUI_ACTIONBAR_PETBAR_HORIZONTAL = "Enable horizontal pet bar"
L_GUI_ACTIONBAR_STANCEBAR_MOUSEOVER = "Stance bar on mouseover"
L_GUI_ACTIONBAR_STANCEBAR_HIDE = "Hide stance bar"
L_GUI_ACTIONBAR_STANCEBAR_HORIZONTAL = "Enable horizontal stance bar"
L_GUI_ACTIONBAR_MICROMENU = "Enable micro menu"
L_GUI_ACTIONBAR_MICROMENU_MOUSEOVER = "Micro menu on mouseover"

-- Auras/Buffs/Debuffs
L_GUI_AURA_PLAYER_BUFF_SIZE = "Player buffs size"
L_GUI_AURA_SHOW_SPIRAL = "Spiral on aura icons"
L_GUI_AURA_SHOW_TIMER = "Show cooldown timer on aura icons"
L_GUI_AURA_PLAYER_AURAS = "Auras on player frame"
L_GUI_AURA_TARGET_AURAS = "Auras on target frame"
L_GUI_AURA_FOCUS_DEBUFFS = "DeBuffs on focus frame"
L_GUI_AURA_FOT_DEBUFFS = "DeBuffs on focus target frame"
L_GUI_AURA_PET_DEBUFFS = "DeBuffs on pet frame"
L_GUI_AURA_TOT_DEBUFFS = "DeBuffs on targettarget frame"
L_GUI_AURA_BOSS_BUFFS = "Buffs on boss frame"
L_GUI_AURA_PLAYER_AURA_ONLY = "Only your debuff on target frame"
L_GUI_AURA_DEBUFF_COLOR_TYPE = "Color debuff by type"
L_GUI_AURA_CAST_BY = "Show who cast a buff/debuff in its tooltip"
L_GUI_AURA_CLASSCOLOR_BORDER = "Enable classcolor border for player buffs"

-- Filger
L_GUI_FILGER = "Timers (Filger)"
L_GUI_FILGER_ENABLE = "Enable Filger"
L_GUI_FILGER_TEST_MODE = "Test icon mode"
L_GUI_FILGER_MAX_TEST_ICON = "The number of icons to the test"
L_GUI_FILGER_SHOW_TOOLTIP = "Show tooltip"
L_GUI_FILGER_DISABLE_CD = "Disable cooldowns"
L_GUI_FILGER_BUFFS_SIZE = "Buffs size"
L_GUI_FILGER_COOLDOWN_SIZE = "Cooldowns size"
L_GUI_FILGER_PVP_SIZE = "PvP debuffs size"

-- Unit Frames options
L_GUI_UF_ENABLE = "Enable unit frames"
L_GUI_UF_OWN_COLOR = "Set your color for health bars"
L_GUI_UF_UF_COLOR = "Color of Health Bars (if own color is enabled)"
L_GUI_UF_ENEMY_HEALTH_COLOR = "Enemy target healthbar is red"
L_GUI_UF_TOTAL_VALUE = "Display of info text on player and target with XXXX/Total"
L_GUI_UF_COLOR_VALUE = "Health/mana value is colored"
L_GUI_UF_BAR_COLOR_VALUE = "Health bar color by current health remaining"
L_GUI_UF_LINES = "Show Player and Target lines"
L_GUI_UF_UNIT_CASTBAR = "Show castbars"
L_GUI_UF_CASTBAR_ICON = "Show castbar icons"
L_GUI_UF_CASTBAR_LATENCY = "Castbar latency"
L_GUI_UF_CASTBAR_TICKS = "Castbar ticks"
L_GUI_UF_SHOW_PET = "Show pet frame"
L_GUI_UF_SHOW_FOCUS = "Show focus frame"
L_GUI_UF_SHOW_TOT = "Show target of target frame"
L_GUI_UF_SHOW_BOSS = "Show boss frames"
L_GUI_UF_BOSS_RIGHT = "Boss frames on the right"
L_GUI_UF_SHOW_ARENA = "Show arena frames"
L_GUI_UF_ARENA_RIGHT = "Arena frames on the right"
L_GUI_UF_BOSS_DEBUFFS = "Number of debuffs on the boss frames"
L_GUI_UF_BOSS_BUFFS = "Number of buffs on the boss frames"
L_GUI_UF_ICONS_PVP = "Mouseover PvP text(not icons) on player and target frames"
L_GUI_UF_ICONS_COMBAT = "Combat icon"
L_GUI_UF_ICONS_RESTING = "Resting icon for low lvl chars"
L_GUI_UF_PORTRAIT_ENABLE = "Enable player/target portraits"
L_GUI_UF_PORTRAIT_CLASSCOLOR_BORDER = "Classcolor border for portraits"
L_GUI_UF_PORTRAIT_HEIGHT = "Portrait height"
L_GUI_UF_PORTRAIT_WIDTH = "Portrait width"
L_GUI_UF_PLUGINS_GCD = "Global cooldown spark on player frame"
L_GUI_UF_PLUGINS_SWING = "Enable swing bar"
L_GUI_UF_PLUGINS_REPUTATION_BAR = "Enable Reputation bar"
L_GUI_UF_PLUGINS_EXPERIENCE_BAR = "Enable Experience bar"
L_GUI_UF_PLUGINS_FRIENDSHIP_BAR = "Friendship bar"
L_GUI_UF_PLUGINS_ARTIFACT_BAR = "Artifact Power bar"
L_GUI_UF_PLUGINS_SMOOTH_BAR = "Smooth bar"
L_GUI_UF_PLUGINS_ENEMY_SPEC = "Show enemy talent spec"
L_GUI_UF_PLUGINS_COMBAT_FEEDBACK = "Combat text on player/target frame"
L_GUI_UF_PLUGINS_FADER = "Fade unit frames"
L_GUI_UF_PLUGINS_DIMINISHING = "Diminishing Returns icons on arena frames"

-- Unit Frames Class bar options
L_GUI_UF_PLUGINS_CLASS_BAR = "Class Power Bars"
L_GUI_UF_PLUGINS_COMBO_BAR = "Enable Rogue/Druid Combo bar"
L_GUI_UF_PLUGINS_COMBO_BAR_ALWAYS = "Always show Combo bar for Druid"
L_GUI_UF_PLUGINS_COMBO_BAR_OLD = "Show combo point on the target"
L_GUI_UF_PLUGINS_ARCANE_BAR = "Enable Arcane Charge bar"
L_GUI_UF_PLUGINS_CHI_BAR = "Enable Chi bar"
L_GUI_UF_PLUGINS_STAGGER_BAR = "Enable Stagger bar (for Monk Tanks)"
L_GUI_UF_PLUGINS_HOLY_BAR = "Enable Holy Power bar"
L_GUI_UF_PLUGINS_SHARD_BAR = "Enable Shards bar"
L_GUI_UF_PLUGINS_RUNE_BAR = "Enable Rune bar"
L_GUI_UF_PLUGINS_TOTEM_BAR = "Enable Totem bar"
L_GUI_UF_PLUGINS_RANGE_BAR = "Enable Range bar (for Priest)"

-- Raid Frames options
L_GUI_UF_BY_ROLE = "Sorting players in group by role"
L_GUI_UF_AGGRO_BORDER = "Aggro border"
L_GUI_UF_DEFICIT_HEALTH = "Raid deficit health"
L_GUI_UF_SHOW_PARTY = "Show party frames"
L_GUI_UF_SHOW_RAID = "Show raid frames"
L_GUI_UF_VERTICAL_HEALTH = "Vertical orientation of health"
L_GUI_UF_ALPHA_HEALTH = "Alpha of healthbars when 100%hp"
L_GUI_UF_SHOW_RANGE = "Show range opacity for raidframes"
L_GUI_UF_RANGE_ALPHA = "Alpha of unitframes when unit is out of range"
L_GUI_UF_SOLO_MODE = "Show player frame always"
L_GUI_UF_PLAYER_PARTY = "Show player frame in party"
L_GUI_UF_SHOW_TANK = "Show raid tanks"
L_GUI_UF_SHOW_TANK_TT = "Show raid tanks target target"
L_GUI_UF_RAID_GROUP = "Number of groups in raid"
L_GUI_UF_RAID_VERTICAL_GROUP = "Vertical raid groups (only for heal layout)"
L_GUI_UF_ICONS_LEADER = "Leader icon, assistant icon, master loot icon on frames"
L_GUI_UF_ICONS_ROLE = "Role icon on frames"
L_GUI_UF_ICONS_RAID_MARK = "Raid marks"
L_GUI_UF_ICONS_READY_CHECK = "Ready check icons"
L_GUI_UF_PLUGINS_DEBUFFHIGHLIGHT_ICON = "Debuff highlight texture + icon"
L_GUI_UF_PLUGINS_AURA_WATCH = "Raid debuff icons (from the list)"
L_GUI_UF_PLUGINS_AURA_WATCH_TIMER = "Timer on raid debuff icons"
L_GUI_UF_PLUGINS_PVP_DEBUFFS = "Show also PvP debuff icons (from the list)"
L_GUI_UF_PLUGINS_HEALCOMM = "Show incoming heal on frame"
L_GUI_UF_PLUGINS_AUTO_RESURRECTION = "Auto cast resurrection on middle-click (doesn't work with Clique)"

-- Panel options
L_GUI_TOP_PANEL = "Top Panel"
L_GUI_TOP_PANEL_ENABLE = "Enable top panel"
L_GUI_TOP_PANEL_MOUSE = "Top panel on mouseover"
L_GUI_TOP_PANEL_WIDTH = "Panel width"
L_GUI_TOP_PANEL_HEIGHT = "Panel height"

-- Stats options
L_GUI_STATS = "Stats"
L_GUI_STATS_BG = "Battleground"
L_GUI_STATS_CLOCK = "Clock"
L_GUI_STATS_LATENCY = "Latency"
L_GUI_STATS_MEMORY = "Memory"
L_GUI_STATS_FPS = "FPS"
L_GUI_STATS_EXPERIENCE = "Experience"
L_GUI_STATS_COORDS = "Coords"
L_GUI_STATS_LOCATION = "Location"
L_GUI_STATS_CURRENCY_ARCHAEOLOGY = "Show Archaeology Fragments under currency tab"
L_GUI_STATS_CURRENCY_COOKING = "Show Cooking under currency tab"
L_GUI_STATS_CURRENCY_PROFESSIONS = "Show Profession Tokens under currency tab"
L_GUI_STATS_CURRENCY_RAID = "Show Raid Seals under currency tab"
L_GUI_STATS_CURRENCY_PVP = "Show PvP Currency under currency tab"
L_GUI_STATS_CURRENCY_MISCELLANEOUS = "Show Miscellaneous Currency under currency tab"

-- Error options
L_GUI_ERROR = "Errors"
L_GUI_ERROR_BLACK = "Hide errors from black list"
L_GUI_ERROR_WHITE = "Show errors from white list"
L_GUI_ERROR_HIDE_COMBAT = "Hide all errors in combat"
